// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestCase1Test
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Dispose();
        driver.Quit();
    }

    [Test]
    public void testCase1()
    {
        driver.Navigate().GoToUrl("http://seleniumdemo.somee.com/");
        driver.Manage().Window.Size = new System.Drawing.Size(976, 1040);
        driver.FindElement(By.Id("Year")).Click();
        driver.FindElement(By.Id("Year")).SendKeys("2024");
        driver.FindElement(By.Id("Month")).Click();
        driver.FindElement(By.Id("Month")).SendKeys("2");
        driver.FindElement(By.Id("Day")).Click();
        driver.FindElement(By.Id("Day")).SendKeys("29");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.Close();
    }
}
